### ISSUE TITLE
Xvnc starts, but no windowmanager is started at all

### ISSUE THREAD

**Issue by mansam-ger** [michalsrb/vncmanager#1]
Hi Michal,

I did set up your vncmanager and I can connect to the vncserver. But I am not able to get any Windows manager started. It seems that ~/.vnc/xstartup is not read at all. I do only get a black screen in vnc viewer.

Xvnc[1629]: Connections: closed: ::0 (Clean disconnection)
Xvnc[1629]: EncodeManager: Framebuffer updates: 1
Xvnc[1629]: EncodeManager:   Tight:
Xvnc[1629]: EncodeManager:     Solid: 1 rects, 786.432 kpixels
Xvnc[1629]: EncodeManager:            16 B (1:196609 ratio)
Xvnc[1629]: EncodeManager:   Total: 1 rects, 786.432 kpixels
Xvnc[1629]: EncodeManager:          16 B (1:196609 ratio)
Xvnc[1629]: VNCServerST: MaxDisconnectionTime reached, exiting
with-vnc-key.sh[1624]: Accepted client 33517456.
Xvnc[1683]: vncext: VNC extension running!
Xvnc[1683]: vncext: inetd wait
Xvnc[1683]: vncext: created VNC server for screen 0
with-vnc-key.sh[1624]: Spawned Xvnc (id: #1, pid: 1683, display: 0)
with-vnc-key.sh[1624]: Opening connection to Xvnc #1
Xvnc[1683]: Connections: accepted: ::0
Xvnc[1683]: SConnection: Client needs protocol version 3.8
Xvnc[1683]: SConnection: Client requests security type None(1)
Xvnc[1683]: VNCSConnST: Server default pixel format depth 24 (32bpp) little-endian rgb888
Xvnc[1683]: VNCSConnST: Client pixel format depth 24 (32bpp) little-endian rgb888
with-vnc-key.sh[1624]: Disconnected client 33517456.
with-vnc-key.sh[1624]: Closing connection to Xvnc #1

do you have any hint for me?

**Comment by michalsrb** [comment]
Hi,

vncmanager does not start the session using ~/.vnc/xstartup, it contacts local display manager (xdm/kdm/gdm/...) using the XDMCP protocol. The display manager will then display login screen in the Xvnc which you can use to select user and login into new session. So you have to enable XDMCP in your display manager (and you must use one that supports it, for example not sddm).

Starting the session using some other mechanism would be interesting feature. However, in the use case I expected, vncmanager is running as system service. So if someone connects over VNC, it has no way of knowing which user it is and which ~/.vnc/xstartup it should use. There must be some login screen. And that is what display managers are for.

**Comment by mansam-ger** [comment]
oh well I got this wrong then, thanks for your help. I will try it tomorrow.
