### ISSUE TITLE
If vncmanager is running no user can log in locally 

### ISSUE THREAD

**Issue by januhlir** [michalsrb/vncmanager#2]
I discovered something what looks like bug in vncmanager, or if not bug, then massive limitation; a limitation not clearly declared in the openSUSE manual:
when vncmanager service is running - users can log in ONLY using VNC, but not locally. 

When vncmanager is running, and I attempt to login locally, GDM starts, shows standard login screen, with user list, but every login attempt ends with sudden return to GDM without any explanation and without any traces in logs. Any error whatsoever anywhere. Any warning, any hint. Just magical return back to GDM. But at the same time I was able to log in via VNC. It took me a lot of head scratching to figure out the culprit - vncmanager. When I disable the service, I was immediately able to login locally. 

I really like vncmanager, I wanted persistent sessions and using vncmanager is an easy and straightforward solution. Well, at least it seemed to be. I set it us using this great manual:  
https://doc.opensuse.org/documentation/leap/reference/html/book.opensuse.reference/cha.vnc.html#vnc.persistent.vncmanager  
4.4.2 VNC Session Initiated Using vncmanager  

I use my box as a home server, experimental server, mostly accessing it by ssh or VNC, but it also doubles as my HTPC/Kodi box, because it sits next to my TV; and I also occasionally log in locally, using TV as monitor. If vncmanager is used, I cannot use it as Kodi box or log in directly. This means vncmanager would be a no-go for me and that's a shame.

This issue is also discussed in openSUSE Forum thread:  
https://forums.opensuse.org/showthread.php/535175-Bug-in-vncmanager-If-running-no-one-can-log-in-locally.

How to verify that vncmanager is the driving service behind VNC:
````
$ ps ax | grep -i vncmanager
 /usr/bin/vncmanager
 /usr/bin/vncmanager-controller --tray --start-setup

$ systemctl status vncmanager
● vncmanager.service - VNC manager
   Loaded: loaded (/usr/lib/systemd/system/vncmanager.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-02-17 21:08:10 GMT; 2h 33min ago
 Main PID: 1177 (vncmanager)
    Tasks: 8 (limit: 4915)
   CGroup: /system.slice/vncmanager.service
           ├─1177 /usr/bin/vncmanager
           └─1916 /usr/bin/Xvnc -log *:syslog:30,TcpSocket:syslog:-1 -inetd -MaxDisconnectionTime=5 -securitytypes=none -displayfd 10 -geometry 102>

$ systemctl status xvnc.socket
● xvnc.socket - Xvnc Server
   Loaded: loaded (/usr/lib/systemd/system/xvnc.socket; disabled; vendor preset: disabled)
   Active: inactive (dead)
````

**Comment by michalsrb** [comment]
This is certainly a bug, local login is meant to work just fine, vncmanager should not affect it.

The return back to GDM is most likely because the X or the desktop session crashed. Note that Gnome has the limitation that one user can be logged in at most once at time on the machine. Other desktop environments do not have this limitation.

1. Which version of openSUSE are you using?
2. Is there any (perhaps disconnected) remote session running?
3. Please try if you could log in with different user or into a different desktop environment.
4. Could you try if it happens with different display manager, e.g. SDDM?

**Comment by michalsrb** [comment]
I just noticed you opened also bug in openSUSE bugzilla:
https://bugzilla.opensuse.org/show_bug.cgi?id=1128989

Let's continue there. I'll keep this issue open here until it is resolved.

**Comment by sndirsch** [comment]
> I just noticed you opened also bug in openSUSE bugzilla:
> https://bugzilla.opensuse.org/show_bug.cgi?id=1128989
> 
> Let's continue there. I'll keep this issue open here until it is resolved.

Bug has been closed, so this issue can be closed as well. ;-)
